apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-k8s
  annotations:
    github.com/project-slug: gabdzo/backstage-k8s
    'backstage.io/kubernetes-id': backstage-k8s
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
